title: BetterPack
description: A Universal Node.js Package Manager CLI
remote_theme: just-the-docs/just-the-docs

color_scheme: dark

url: https://involvex.github.io/betterpack

logo: "/assets/logo.png"

aux_links:
  "View on GitHub":
    - "https://github.com/involvex/betterpack"

nav_links:
  - title: '<i class="material-icons">info</i> Summary'
    url: "#betterpack---a-universal-nodejs-package-manager-cli"
  - title: '<i class="material-icons">download</i> Installation'
    url: "#installation"
  - title: '<i class="material-icons">code</i> Development'
    url: "#how-it-works"
  - title: '<i class="material-icons">favorite</i> Support'
    url: "#support-the-project"
