title: BetterPack
description: A Universal Node.js Package Manager CLI
remote_theme: just-the-docs/just-the-docs

color_scheme: dark

url: https://involvex.github.io/betterpack

logo: "/assets/logo.png"

aux_links:
  "View on GitHub":
    - "https://github.com/involvex/betterpack"
